// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssmcaehlrpbvdttrhlvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzbWNhZWhscnBidmR0dHJobHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTE1NTEsImV4cCI6MjA2OTI4NzU1MX0.318_bR0QtjH5NIYpXEzeMyf4aLw7eLmuxvSAJWKVorg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});